POST {{host}}/api/v2/user/register
Content-Type: application/json

{
  "username": "test",
  "email": "test@test.pl",
  "password": "Start00!",
  "userWalletBalance": 10000
}

###

POST {{host}}/api/v2/user/login
Content-Type: application/json

{
  "username": "test",
  "password": "Start00!"
}

###

GET {{host}}/api/v2/user/wallet
Authorization: //Paste authorization header content (Bearer token) here