POST {{host}}/api/v2/user/register
Content-Type: application/json

{
  "username": "test",
  "email": "test@test.pl",
  "password": "Start00!",
  "userWalletBalance": 10000
}

###

POST {{host}}/api/v2/user/login
Content-Type: application/json

{
  "username": "test",
  "password": "Start00!"
}

###

GET {{host}}/api/v2/user/wallet
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiYXV0aG9yaXRpZXMiOlt7ImF1dGhvcml0eSI6IlVTRVIifV0sImlhdCI6MTY0OTg0MDExNiwiZXhwIjoxNjQ5ODg3MjAwfQ.Jgtz9ZykL2HOjOckAO9Giwwv7wDYRbuL55_5KQF8boE