CREATE TABLE public__transaction
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    wallet_id                 BIGINT                                  NOT NULL,
    transaction_type          VARCHAR(255)                            NOT NULL,
    transaction_status        VARCHAR(255)                            NOT NULL,
    transaction_create_date   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    transaction_process_date  TIMESTAMP WITHOUT TIME ZONE,
    balance_blocked           DECIMAL,
    balance_after_transaction DECIMAL,
    stock_ticker              VARCHAR(255)                            NOT NULL,
    stock_price_limit         DECIMAL                                 NOT NULL,
    stock_quantity            INTEGER                                 NOT NULL,
    CONSTRAINT pk_public__transaction PRIMARY KEY (id)
);

CREATE TABLE public__user
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    active    BOOLEAN                                 NOT NULL,
    username  VARCHAR(255)                            NOT NULL,
    email     VARCHAR(255)                            NOT NULL,
    password  VARCHAR(255)                            NOT NULL,
    user_role VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_public__user PRIMARY KEY (id)
);

CREATE TABLE public__user_stock
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    wallet_id              BIGINT                                  NOT NULL,
    ticker                 VARCHAR(255)                            NOT NULL,
    quantity_available     INTEGER                                 NOT NULL,
    quantity_blocked       INTEGER                                 NOT NULL,
    average_purchase_price DECIMAL                                 NOT NULL,
    CONSTRAINT pk_public__user_stock PRIMARY KEY (id)
);

CREATE TABLE public__user_wallet
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id              BIGINT                                  NOT NULL,
    balance_available    DECIMAL                                 NOT NULL,
    balance_blocked      DECIMAL                                 NOT NULL,
    last_day_value       DECIMAL                                 NOT NULL,
    last_day_update_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_public__user_wallet PRIMARY KEY (id)
);

ALTER TABLE public__user_stock
    ADD CONSTRAINT uc_fa6fd5de69c0e1fd33604f54f UNIQUE (wallet_id, ticker);

ALTER TABLE public__user
    ADD CONSTRAINT uc_public__user_email UNIQUE (email);

ALTER TABLE public__user
    ADD CONSTRAINT uc_public__user_username UNIQUE (username);

ALTER TABLE public__user_wallet
    ADD CONSTRAINT uc_public__user_wallet_user UNIQUE (user_id);