CREATE TABLE public__user_favourite_stock
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT                                  NOT NULL,
    ticker  VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_public__user_favourite_stock PRIMARY KEY (id)
);

ALTER TABLE public__user_favourite_stock
    ADD CONSTRAINT uc_public__user_favourite_stock_user_ticker UNIQUE (user_id, ticker);
