apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-app-deployment
  labels:
    app: stock-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-app
  template:
    metadata:
      labels:
        app: stock-app
    spec:
      containers:
        - name: stock-app
          imagePullPolicy: Never
          image: stock-app:1.0
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: database-user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-user-password
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: stock-app-configmap
                  key: database-url
---
apiVersion: v1
kind: Service
metadata:
  name: stock-app-service
spec:
  selector:
    app: stock-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
