spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://stock-exchange-app-database:5432/postgres
    username: postgres
    password: postgres
  data:
    redis:
      host: stock-exchange-app-redis

application:
  jwt.secretKey: 11111111111111111111111111111111

frontend.url: http://localhost:3000

logging:
  level:
    com.s1gawron.stockexchange: DEBUG