spring:
  application:
    name: stock-exchange-app
  flyway:
    default-schema: ${spring.application.name}
  jpa:
    properties:
      hibernate:
        default_schema: ${spring.application.name}

springdoc:
  api-docs:
    path: /api-docs

finnhub:
  baseUrl: https://finnhub.io/api/v1
  webSocketUrl: wss://ws.finnhub.io?token=

logging:
  structured:
    format:
      file: ecs
  file:
    name: backend/logs/stock-exchange-app.log

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus